version: '3.9'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  mongo:
    image: 'mongo'
    restart: always
    ports:
      - '27017:27017'
  backend:
    restart: on-failure
    build: .
    volumes:
      - .:/app
    depends_on:
       - redis
    ports:
      - '3000:3000'
